BEGIN;

-- Rename Cpf to Email
DROP INDEX IF EXISTS "IX_usuarios_Cpf";
ALTER TABLE usuarios RENAME COLUMN "Cpf" TO "Email";
ALTER TABLE usuarios ALTER COLUMN "Email" TYPE character varying(255);
CREATE UNIQUE INDEX "IX_usuarios_Email" ON usuarios ("Email");

-- Create operador_condominios table
CREATE TABLE IF NOT EXISTS operador_condominios (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OperadorId" integer NOT NULL REFERENCES usuarios("Id") ON DELETE CASCADE,
    "CondominioId" integer NOT NULL REFERENCES condominios("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_operador_condominios_CondominioId" ON operador_condominios ("CondominioId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_operador_condominios_OperadorId_CondominioId" ON operador_condominios ("OperadorId", "CondominioId");

-- Register migration
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260606180000_CpfToEmail_OperadorCondominio', '8.0.0')
ON CONFLICT DO NOTHING;

-- Update CPF values to email
UPDATE usuarios SET "Email" = 'admin@prolar.com' WHERE "Nome" = 'Administrador';
UPDATE usuarios SET "Email" = 'operador@prolar.com' WHERE "Nome" = 'Operador Padr' || chr(227) || 'o';
UPDATE usuarios SET "Email" = 'fiscal@prolar.com' WHERE "Nome" = 'Fiscal Padr' || chr(227) || 'o';

-- Re-hash passwords with BCrypt (the seed uses different cost factor)
-- We'll let the API re-seed with correct passwords instead
DELETE FROM usuarios;

COMMIT;
