FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["web/HidrometroApp.Web.csproj", "HidrometroApp.Web/"]
RUN dotnet restore "HidrometroApp.Web/HidrometroApp.Web.csproj"

COPY web/ HidrometroApp.Web/
RUN dotnet publish "HidrometroApp.Web/HidrometroApp.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "HidrometroApp.Web.dll"]
