// <auto-generated />
using HidrometroApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HidrometroApp.Infrastructure.Migrations
{
    [DbContext(typeof(HidrometroDbContext))]
    [Migration("20260606180000_CpfToEmail_OperadorCondominio")]
    partial class CpfToEmail_OperadorCondominio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // model snapshot handled by HidrometroDbContextModelSnapshot
        }
    }
}
