// <auto-generated />
using System;
using HidrometroApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HidrometroApp.Infrastructure.Migrations
{
    [DbContext(typeof(HidrometroDbContext))]
    partial class HidrometroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HidrometroApp.Core.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DadosAntes")
                        .HasColumnType("text");

                    b.Property<string>("DadosDepois")
                        .HasColumnType("text");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Origem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("integer");

                    b.Property<string>("Tabela")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.Condominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("QtdUnidades")
                        .HasColumnType("integer");

                    b.Property<string>("TipoMedidor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("condominios", (string)null);
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.HistoricoConsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ConsumoM3")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LeituraAnterior")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("LeituraAtual")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<int?>("OsId")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OsId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("historico_consumo", (string)null);
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.HistoricoTrocaHidrometro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DataTroca")
                        .HasColumnType("date");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<string>("NumeroSerieAnterior")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroSerieNovo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("historico_troca_hidrometro", (string)null);
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.LeituraHidrometro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ConfiancaIa")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("FotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MotivoRejeicao")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OsId")
                        .HasColumnType("integer");

                    b.Property<string>("QualidadeFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("PrioridadeOperador")
                        .HasColumnType("boolean");

                    b.Property<bool>("RecomendacaoRevisao")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SuspeitaVazamento")
                        .HasColumnType("boolean");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ValidadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ValidadoPorId")
                        .HasColumnType("integer");

                    b.Property<int>("ValorLitros")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ValorM3")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal?>("ValorM3Validado")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("OsId");

                    b.HasIndex("UnidadeId");

                    b.HasIndex("ValidadoPorId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_leituras_status");

                    b.ToTable("leituras_hidrometro", (string)null);
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("CondominioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FiscalId")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FiscalId");

                    b.HasIndex("CondominioId", "Mes", "Ano")
                        .IsUnique();

                    b.ToTable("ordens_servico", (string)null);
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int>("CondominioId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId", "Numero")
                        .IsUnique();

                    b.ToTable("unidades", (string)null);
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.OperadorCondominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CondominioId")
                        .HasColumnType("integer");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.HasIndex("OperadorId", "CondominioId")
                        .IsUnique();

                    b.ToTable("operador_condominios", (string)null);
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.Auditoria", b =>
                {
                    b.HasOne("HidrometroApp.Core.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.HistoricoConsumo", b =>
                {
                    b.HasOne("HidrometroApp.Core.Models.OrdemServico", "Os")
                        .WithMany()
                        .HasForeignKey("OsId");

                    b.HasOne("HidrometroApp.Core.Models.Unidade", "Unidade")
                        .WithMany("HistoricoConsumo")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Os");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.HistoricoTrocaHidrometro", b =>
                {
                    b.HasOne("HidrometroApp.Core.Models.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HidrometroApp.Core.Models.Unidade", "Unidade")
                        .WithMany("HistoricoTrocas")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPor");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.LeituraHidrometro", b =>
                {
                    b.HasOne("HidrometroApp.Core.Models.Usuario", "CriadoPor")
                        .WithMany("LeiturasRegistradas")
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HidrometroApp.Core.Models.OrdemServico", "Os")
                        .WithMany("Leituras")
                        .HasForeignKey("OsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HidrometroApp.Core.Models.Unidade", "Unidade")
                        .WithMany("Leituras")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HidrometroApp.Core.Models.Usuario", "ValidadoPor")
                        .WithMany("LeiturasValidadas")
                        .HasForeignKey("ValidadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPor");

                    b.Navigation("Os");

                    b.Navigation("Unidade");

                    b.Navigation("ValidadoPor");
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.OrdemServico", b =>
                {
                    b.HasOne("HidrometroApp.Core.Models.Condominio", "Condominio")
                        .WithMany("OrdensServico")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HidrometroApp.Core.Models.Usuario", "Fiscal")
                        .WithMany("OrdensServico")
                        .HasForeignKey("FiscalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Condominio");

                    b.Navigation("Fiscal");
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.Unidade", b =>
                {
                    b.HasOne("HidrometroApp.Core.Models.Condominio", "Condominio")
                        .WithMany("Unidades")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.OperadorCondominio", b =>
                {
                    b.HasOne("HidrometroApp.Core.Models.Condominio", "Condominio")
                        .WithMany("Operadores")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HidrometroApp.Core.Models.Usuario", "Operador")
                        .WithMany("CondominiosAtribuidos")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.Condominio", b =>
                {
                    b.Navigation("Operadores");

                    b.Navigation("OrdensServico");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.OrdemServico", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.Unidade", b =>
                {
                    b.Navigation("HistoricoConsumo");

                    b.Navigation("HistoricoTrocas");

                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("HidrometroApp.Core.Models.Usuario", b =>
                {
                    b.Navigation("CondominiosAtribuidos");

                    b.Navigation("LeiturasRegistradas");

                    b.Navigation("LeiturasValidadas");

                    b.Navigation("OrdensServico");
                });
#pragma warning restore 612, 618
        }
    }
}
